trigger:
  branches:
    include:
      - main
  
  paths:
    include:
      - app/backend/**
      - pipelines/backend-ci.yaml

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self

  - bash: |
      cd app/backend
      docker build -t issue-tracker-backend:test .
    displayName: Build backend Docker image

  - bash: |
      set -e

      docker run -d --name backend-test -p 8000:8000 issue-tracker-backend:test

      sleep 5

      curl --fail http://localhost:8000/health

      docker stop backend-test
    displayName: Test backend container

  - task: AzureCLI@2
    displayName: Push backend image to ACR
    inputs:
      azureSubscription: sc-cit-azure
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        set -e

        az acr login --name crcitdevfrc

        docker tag \
          issue-tracker-backend:test \
          crcitdevfrc.azurecr.io/backend:latest

        docker push \
          crcitdevfrc.azurecr.io/backend:latest

  - task: AzureCLI@2
    displayName: Deploy backend to Container Apps
    inputs:
      azureSubscription: sc-cit-azure
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        set -e

        az containerapp update \
          --name ca-cit-backend-dev-frc-001 \
          --resource-group rg-cit-workload-dev-frc-001 \
          --image crcitdevfrc.azurecr.io/backend:latest \
          --revision-suffix build-$(Build.BuildId)